### ISSUE TITLE
Feature: Allow "AND" for termination conditions

### ISSUE THREAD

**Issue by Thaigun** [Bam4d/Griddly#161]
Docs say this about Win conditions: 
_If any of these conditions are met, the player associated with this condition will win the game_. 
It would be useful to be able to use AND, instead of OR. Something like 
```
Termination:
  Win:
    - and: [eq: [players_alive, 1], eq: [plr_done, 0]]
    - gte: [_steps: 100]
``` 
or
```
Termination:
  Win:
    - and: 
      - eq: [players_alive, 1]
      - eq: [plr_done, 0]
    - gte: [_steps: 100]
```
would mean the player wins if [a global variable players_alive reaches 1 and this player is not `player_done`] or `steps` reaches 1000.

Again, depending on the implementation details, similar structure could be used for action preconditions to let the user decide whether they need AND/OR.
