### ISSUE TITLE
Allow VECTOR view to have additional depths to differentiate different tiles for a single object

### ISSUE THREAD

**Issue by aadharna** [Bam4d/Griddly#232]
Right now in the VECTOR view the state space is the same even if an agent is in two different states. 

e.g. 
![image](https://user-images.githubusercontent.com/16660757/183113328-301de768-3612-4739-ae72-13e05227f760.png)

Can we add extend the OneHotTensor to have multiple slices if an object has multiple views?

Maybe we can add it via the VECTOR observer in the yaml similar to the BLOCK_2D ones and if that is greater than one, we increase the number of dim from shape [y, x, n_objects] to [y, x, num_object + n_tiles_per_object]?

```
Objects:
  - Name: gnome
    Z: 2
    MapCharacter: g
    InitialActions:
      - Action: give_feedback
        ActionId: 1
        Delay: 1
    Variables:
      - Name: spotlight
        InitialValue: 0
      - Name: spider_counter
        InitialValue: 0
    Observers:
      Isometric:
        - Image: oryx/oryx_iso_dungeon/avatars/gnome-1.png
        - Image: oryx/oryx_iso_dungeon/avatars/spider-fire-1.png
      Block2D:
        - Shape: square
          Color: [ 0.0, 0.8, 0.0 ]
          Scale: 0.5
        - Shape: triangle
          Color: [0.0, 0.5, 0.2]
          Scale: 0.8
      VECTOR:    
        - Color: [a, b, c]
        - Color: [d, e, f]
```
